name: Docker Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if Docker container is running
      run: |
        if [ $(docker ps -q -f name=flask_app_container) ]; then
          docker stop flask_app_container
          docker rm flask_app_container
        fi

    - name: Check if Docker volume exists
      run: |
        if [ $(docker volume ls -q -f name=my_volume) ]; then
          echo "Volume exists"
        else
          docker volume create my_volume
        fi

    - name: Build Docker image
      run: |
        docker build -t my_image:tag .
    
    - name: Run Docker container
      run: |
        docker run --name flask_app_container -d -p 5000:5000 -v my_volume:/app/predctionLogs my_image:tag