name: Docker Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t my_image:tag .
        
    - name: Create Docker Volume
        docker volume create my_volume
    
    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 -v my_volume:/app/predctionLogs my_image:tag 
